apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: carts
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: enableTLS
    value: false
