apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: carts-psql
  namespace: default
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=localhost user=postgres password=3x4mpl3 port=5432 connect_timeout=10 database=dapr_test"
